version: "3.8"
services:
    web:
        image: rkrastev/bgapp-nginx-php-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/bgapp"
        networks:
            - app-network
    db:
        image: rkrastev/bgapp-nginx-php-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
